package metastructs

const (
	// PackageComment is the header comment included in generated files.
	PackageComment = "Autogenerated by metastructs. DO NOT EDIT."

	// MethodReceiver is the receiver for generated methods, ensure that not collide with user's vars.
	MethodReceiver = "myNonCollidingReceiver"
)
