// Package partial contains the generator for a partial struct.
package partial

import (
	"errors"
	"fmt"
	"go/types"
	"io"
	"strings"
	"unicode/utf8"

	"github.com/dave/jennifer/jen"
	"github.com/kytnacode/metastructs/pkg/util"
)

// DefaultPrefix is the default prefix for the struct generated by [Partial].
const DefaultPrefix = "Partial"

// Config is the config for [Partial].
type Config struct {
	Typ          *types.Named
	PkgName      string
	StructName   string
	Suffix       string
	Prefix       *string
	PreserveTags bool
	ForcePointer bool
}

// Partial generates a partial struct for a given type.
func Partial(w io.Writer, cfg Config) error {
	if cfg.PkgName == "" {
		return errors.New("cfg.PkgName is required")
	}

	if cfg.Typ == nil {
		return errors.New("cfg.Typ is required")
	}

	if cfg.Prefix == nil {
		cfg.Prefix = new(string)
		*cfg.Prefix = DefaultPrefix
	}

	if cfg.StructName == "" {
		name := cfg.Typ.Obj().Name()
		r, size := utf8.DecodeRuneInString(name)

		cfg.StructName = *cfg.Prefix + strings.ToUpper(string(r)) + name[size:] + cfg.Suffix
	}

	if cfg.StructName == cfg.Typ.Obj().Name() {
		return errors.New("output struct name is the same as the target, try set cfg>Suffix, cfg.Prefix or cfg.StructName")
	}

	structType, ok := cfg.Typ.Underlying().(*types.Struct)
	if !ok {
		return fmt.Errorf("`%v` is not a struct", cfg.Typ.Obj().Name())
	}

	fields := make([]jen.Code, 0, structType.NumFields())

	for i := range structType.NumFields() {
		field := structType.Field(i)
		structField := jen.Id(field.Name())

		typ := field.Type()

		var indirection int

		for {
			if named, ok := typ.(*types.Named); ok {
				if _, ok := typ.Underlying().(*types.Interface); ok {
					indirection--
				}

				if indirection == 0 {
					structField.Op("*")
				}

				for range indirection {
					structField.Op("*")
				}

				if cfg.ForcePointer {
					structField.Op("*")
				}

				if named.Obj().Pkg().Path() == cfg.Typ.Obj().Pkg().Path() {
					structField.Id(named.Obj().Name())
				} else {
					structField.Qual(named.Obj().Pkg().Path(), named.Obj().Name())
				}

				break
			} else if basic, ok := typ.(*types.Basic); ok {
				structField.Op("*").Id(basic.String())

				break
			} else if pointer, ok := typ.(*types.Pointer); ok {
				typ = pointer.Elem()
				indirection++

				continue
			} else if inter, ok := typ.(*types.Interface); ok {
				structField.Id(inter.String())

				break
			}

			return fmt.Errorf("unsupported type: `%v`", typ.String())
		}

		if cfg.PreserveTags {
			structField.Op("`" + structType.Tag(i) + "`")
		}

		fields = append(fields, structField)
	}

	f := util.NewFile(cfg.PkgName)

	f.Type().Id(cfg.StructName).Struct(fields...)

	return f.Render(w)
}
